<a href="https://colab.research.google.com/github/MinJunJA/knime/blob/master/br_prac2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
#csv reader

import pandas as pd

# .data 파일의 경로 설정
data_file_path = '/content/breast-cancer-wisconsin.data'

# .data 파일을 읽어와 DataFrame으로 변환
data = pd.read_csv(data_file_path, header=None)

# .csv 파일로 저장
csv_file_path = '/content/breast_cancer_data.csv'
data.to_csv(csv_file_path, index=False)

In [14]:
#컬럼명 설정
import pandas as pd

csv_file_path = '/content/breast_cancer_data.csv'

new_columns = ['ID', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
               'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei',
               'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class']

data = pd.read_csv(csv_file_path)

data.columns = new_columns

print(data.head())  # 변경된 컬럼명을 확인하기 위해 데이터 일부 출력

data.to_csv(csv_file_path, index=False)

        ID  Clump Thickness  Uniformity of Cell Size  \
0  1000025                5                        1   
1  1002945                5                        4   
2  1015425                3                        1   
3  1016277                6                        8   
4  1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1

In [15]:
#결측값처리
import numpy as np
df = pd.read_csv('/content/breast_cancer_data.csv')

df['Bare Nuclei'].replace('?', np.nan, inplace=True)
df.dropna(subset=['Bare Nuclei'], axis=0, inplace=True)

In [16]:
#value counter

print(df['Bare Nuclei'].value_counts())

1     402
10    132
2      30
5      30
3      28
8      21
4      19
9       9
7       8
6       4
Name: Bare Nuclei, dtype: int64


In [17]:
#type변경
df['Bare Nuclei'] = df['Bare Nuclei'].astype('int')
print(df.info(), '\n')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 683 entries, 0 to 698
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 64.0 KB
None 



In [18]:
#'id'제거

X = df[['Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses']]
Y = df['Class']

In [20]:
#Normalizer

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [22]:
#Partitioning

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=10)

In [23]:
#모델링

from sklearn import tree
tree_model = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)
tree_model.fit(X_train, y_train)
y_pred = tree_model.predict(X_test)

In [24]:
#Scorer

from sklearn import metrics
matrix = metrics.confusion_matrix(y_test, y_pred)
print(matrix)

report = metrics.classification_report(y_test, y_pred)
print(report)

[[127   4]
 [  2  72]]
              precision    recall  f1-score   support

           2       0.98      0.97      0.98       131
           4       0.95      0.97      0.96        74

    accuracy                           0.97       205
   macro avg       0.97      0.97      0.97       205
weighted avg       0.97      0.97      0.97       205



In [25]:
from sklearn.metrics import accuracy_score

# 정확도 계산
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9707317073170731


In [29]:
#csv reader

import pandas as pd

# .data 파일의 경로 설정
data_file_path = '/content/breast-cancer-wisconsin.data'

# .data 파일을 읽어와 DataFrame으로 변환
data = pd.read_csv(data_file_path, header=None)

# .csv 파일로 저장
csv_file_path = '/content/breast_cancer_data.csv'
data.to_csv(csv_file_path, index=False)

#컬럼명 설정
import pandas as pd

csv_file_path = '/content/breast_cancer_data.csv'

new_columns = ['ID', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
               'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei',
               'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class']

data = pd.read_csv(csv_file_path)

data.columns = new_columns

#print(data.head())  # 변경된 컬럼명을 확인하기 위해 데이터 일부 출력

data.to_csv(csv_file_path, index=False)

#결측값처리
import numpy as np
df = pd.read_csv('/content/breast_cancer_data.csv')

df['Bare Nuclei'].replace('?', np.nan, inplace=True)
df.dropna(subset=['Bare Nuclei'], axis=0, inplace=True)

#value counter

#print(df['Bare Nuclei'].value_counts())

#type변경
df['Bare Nuclei'] = df['Bare Nuclei'].astype('int')
#print(df.info(), '\n')

#'id'제거

X = df[['Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape', 'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses']]
Y = df['Class']

#Normalizer

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

#Partitioning

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=10)

#모델링

from sklearn import tree
tree_model = tree.DecisionTreeClassifier(criterion='entropy', max_depth=5)
tree_model.fit(X_train, y_train)
y_pred = tree_model.predict(X_test)

#Scorer

from sklearn import metrics
matrix = metrics.confusion_matrix(y_test, y_pred)
print(matrix)

report = metrics.classification_report(y_test, y_pred)
print(report)

from sklearn.metrics import accuracy_score

# 정확도 계산
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

[[127   4]
 [  2  72]]
              precision    recall  f1-score   support

           2       0.98      0.97      0.98       131
           4       0.95      0.97      0.96        74

    accuracy                           0.97       205
   macro avg       0.97      0.97      0.97       205
weighted avg       0.97      0.97      0.97       205

Accuracy: 0.9707317073170731


In [30]:
#랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

import pandas as pd

csv_file_path = '/content/breast_cancer_data.csv'

new_columns = ['ID', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
               'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei',
               'Bland Chromatin', 'Normal Nucleoli', 'Mitoses', 'Class']

data = pd.read_csv(csv_file_path)

data.columns = new_columns

data.to_csv(csv_file_path, index=False)

df = pd.read_csv('/content/breast_cancer_data.csv')
df['Bare Nuclei'].replace('?', np.nan, inplace=True)
df.dropna(subset=['Bare Nuclei'], axis=0, inplace=True)
df['Bare Nuclei'] = df['Bare Nuclei'].astype('int')

X = df[['Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
        'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei',
        'Bland Chromatin', 'Normal Nucleoli', 'Mitoses']]
Y = df['Class']

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=10)

rf_model = RandomForestClassifier(n_estimators=100, random_state=10)
rf_model.fit(X_train, y_train)


y_pred = rf_model.predict(X_test)

# 모델 평가
matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(matrix)

report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

# 정확도 계산
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Confusion Matrix:
[[129   2]
 [  2  72]]
Classification Report:
              precision    recall  f1-score   support

           2       0.98      0.98      0.98       131
           4       0.97      0.97      0.97        74

    accuracy                           0.98       205
   macro avg       0.98      0.98      0.98       205
weighted avg       0.98      0.98      0.98       205

Accuracy: 0.9804878048780488
